[tool.poetry]
name = "survey"
version = "0.1.0"
description = ""
authors = ["Gabriele Spina <g.spina@innovazione.gov.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.8"
streamlit = "^1.35.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
